"""PyInstaller build wrapper for EleitorUM.

Reads the canonical version from eleitorum.version.__version__,
generates a Windows PE version resource file (version_info.py),
then invokes PyInstaller to produce a one-folder Windows build.
Finally creates the distribution ZIP and SHA-256 checksum file.

Usage:
    python scripts/build.py            # --onedir (default, D-07)
    python scripts/build.py --onefile  # manual opt-in; slower cold start, AV-scan risk

Output (one-folder):
    dist/EleitorUM/EleitorUM.exe
    EleitorUM-{version}-win64.zip
    EleitorUM-{version}-win64.zip.sha256
"""

from __future__ import annotations

import argparse
import hashlib
import os
import pathlib
import sys
import textwrap
import zipfile

# Add src/ to path so eleitorum.version can be imported without installation
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
from eleitorum.version import __version__  # noqa: E402


def _generate_version_info(version: str) -> None:
    """Write version_info.py for PyInstaller --version-file.

    Generates a VSVersionInfo literal with correct Windows PE metadata fields.
    The file is written to the current directory (repo root).
    """
    parts = tuple(int(x) for x in version.split(".")) + (0,) * 4
    major, minor, patch, build = parts[:4]
    content = textwrap.dedent(f"""\
        # Auto-generated by scripts/build.py — do not edit.
        VSVersionInfo(
          ffi=FixedFileInfo(
            filevers=({major}, {minor}, {patch}, {build}),
            prodvers=({major}, {minor}, {patch}, {build}),
            mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
          ),
          kids=[
            StringFileInfo([
              StringTable('040904B0', [
                StringStruct('CompanyName', ''),
                StringStruct('FileDescription', 'EleitorUM — Normalizador de ficheiros eleitorais'),
                StringStruct('FileVersion', '{version}.0'),
                StringStruct('InternalName', 'EleitorUM'),
                StringStruct('LegalCopyright', 'MIT License'),
                StringStruct('OriginalFilename', 'EleitorUM.exe'),
                StringStruct('ProductName', 'EleitorUM'),
                StringStruct('ProductVersion', '{version}.0'),
              ])
            ]),
            VarFileInfo([VarStruct('Translation', [1033, 1200])])
          ]
        )
        """)
    with open("version_info.py", "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated version_info.py for version {version}")


def _create_zip(version: str) -> pathlib.Path:
    """Create the distribution ZIP from the one-folder build output.

    Walks dist/EleitorUM/ and adds every file to the ZIP under the EleitorUM/
    prefix, so the archive extracts to EleitorUM/EleitorUM.exe etc.
    Returns the path of the created ZIP file.
    """
    zip_name = f"EleitorUM-{version}-win64.zip"
    with zipfile.ZipFile(zip_name, "w", zipfile.ZIP_DEFLATED) as z:
        for f in pathlib.Path("dist/EleitorUM").rglob("*"):
            if f.is_file():
                arcname = f.relative_to("dist")
                z.write(f, arcname)
                print(f"  Added: {arcname}")
    print(f"Created {zip_name}")
    return pathlib.Path(zip_name)


def _write_sha256(zip_path: pathlib.Path) -> None:
    """Compute SHA-256 of the ZIP and write a BSD-style checksum file.

    The checksum format is: <hex_digest>  <filename>
    (two spaces between digest and filename, BSD-style).
    """
    digest = hashlib.sha256(zip_path.read_bytes()).hexdigest()
    sha_path = zip_path.with_suffix(".zip.sha256")
    sha_path.write_text(f"{digest}  {zip_path.name}\n", encoding="utf-8")
    print(f"SHA-256: {digest}  {zip_path.name}")


def main() -> None:
    """Build EleitorUM: generate PE metadata, invoke PyInstaller, create ZIP + SHA-256."""
    parser = argparse.ArgumentParser(
        prog="build.py",
        description="Build EleitorUM Windows distribution artifact.",
    )
    # --onefile: manual opt-in; slower cold start, Windows Defender scan on each launch (D-07)
    parser.add_argument(
        "--onefile",
        action="store_true",
        help=(
            "Bundle as a single EXE instead of one-folder. "
            "Manual opt-in per D-07: slower cold start, AV-scan on each launch."
        ),
    )
    args = parser.parse_args()

    print(f"Building EleitorUM {__version__}...")

    _generate_version_info(__version__)

    # Build the PyInstaller argument list
    pyinstaller_args = [
        "src/eleitorum/__main__.py",
        "--name=EleitorUM",
        "--windowed",
        "--icon=src/eleitorum/resources/icons/EleitorUM.ico",
        "--version-file=version_info.py",
        "--add-data=src/eleitorum/resources/fonts/Inter:resources/fonts/Inter",
        "--clean",
        "--noconfirm",
    ]
    if args.onefile:
        pyinstaller_args.append("--onefile")
    else:
        pyinstaller_args.append("--onedir")

    import PyInstaller.__main__  # noqa: PLC0415 — imported inside main() to avoid loading on --help

    PyInstaller.__main__.run(pyinstaller_args)

    zip_path = _create_zip(__version__)
    _write_sha256(zip_path)

    print(f"Build complete. Distribution artifact: {zip_path.name}")


if __name__ == "__main__":
    main()
